### ISSUE TITLE
Use of dcterms and dct prefixes

### ISSUE THREAD

**Issue by barthelemyf** [SEMICeu/StatDCAT-AP#1]
The next version of the StatDCAT-AP specification needs to align the use of the dcterms and dct prefixes.

**Comment by makxdekkers** [comment]
The specification 1.0.0 uses dct: as the namespace prefix for DCMI metadata terms (http://purl.org/dcterms/) with the exception of the second RDF example in Annex VIII.2. As the example correctly declares the prefix (@prefix dcterms: <http://purl.org/dc/terms/), the example is not wrong. However, to make the specification consistent, Annex VIII.2 will be revised in the next bug fix/editorial release.
